- name: install pdf reader
  pacman: name=evince state=installed
  become: true

- name: install markdown editor
  pacman: name=ghostwriter state=installed
  become: true

- name: install libreoffice
  pacman:
    state: installed
    package:
    - libreoffice-fresh
    - libreoffice-fresh-be
    - libreoffice-fresh-ru
  become: true
