# zsh basic configuration
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob notify
unsetopt autocd beep nomatch
bindkey -e

ZSH_CACHE_DIR=~/.cache/zsh

# zsh completion
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors ''
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR

# zsh prompt
autoload -Uz colors
colors
function git_prompt_info() {
  local ref
  ref=$(command git symbolic-ref HEAD 2> /dev/null) || \
  ref=$(command git rev-parse --short HEAD 2> /dev/null) || return 0

  local dirty=''
  if [[ -n $(command git status --porcelain --ignore-submodules=dirty --untracked-files=no 2> /dev/null | tail -n1) ]]; then
    dirty='*'
  fi
  echo "(${ref#refs/heads/}$dirty)"
}
function prompt_char {
  if [ $UID -eq 0 ];
    then echo "#";
  else
    echo $;
  fi
}
PROMPT="%(!.%{$fg_bold[red]%}.%{$fg_bold[green]%}%n@)%m %{$fg_bold[blue]%}%(!.%1~.%~) $(git_prompt_info)%_$(prompt_char)%{$reset_color%} "

# Write some info to terminal title.
# This is seen when the shell prompts for input.
function precmd {
  print -Pn "\e]0;zsh%L %(1j,%j job%(2j|s|); ,)%~\a"
}
# Write command and args to terminal title.
# This is seen while the shell waits for a command to complete.
function preexec {
  printf "\033]0;%s\a" "$1"
}

# application-specific logic
for f in .zshrc.d/*.sh(.N); do source $f; done
