[icons]
icons = "awesome5"

[theme]
theme = "native"
[theme.overrides]
idle_fg = "#a3b1b1"
info_fg = "#a3b1b1"
good_fg = "#a3b1b1"
warning_bg = "#ebcb8b" # yellow
warning_fg = "#000000"
critical_bg = "#bf616a" # red
critical_fg = "#000000"

[[block]]
block = "cpu"
interval = 1
format = "$icon $utilization.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
interval = 5
warning_mem = 60
critical_mem = 90

[[block]]
block = "net"
device = "wlan0"
format = " $icon $signal_strength $ssid "
interval = 2

[[block]]
block = "battery"
format = " $icon $percentage $time "
interval = 10

[[block]]
block = "sound"
device_kind = "sink"
format = " $icon $volume "
show_volume_when_muted = true

[[block]]
block = "sound"
device_kind = "source"
format = " $icon "
show_volume_when_muted = true
[block.theme_overrides]
# red background when the is enabled
idle_bg = "#bf616a" # red
idle_fg = "#000000"
warning_bg = "#000000"
warning_fg = "#a3b1b1"

[[block]]
block = "maildir"
interval = 60
format = " $icon $status.eng(w:1) "
inboxes = ["{{ ansible_env.HOME }}/maildir/INBOX"]
threshold_warning = 1
threshold_critical = 100
display_type = "new"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M') "
[block.theme_overrides]
idle_fg = "#ffffff"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
[block.mappings]
"English (US)" = "en"
"Belarusian (N/A)" = "by"
"Russian (N/A)" = "ru"
[block.theme_overrides]
idle_fg = "#000000"
idle_bg = "#70c0ba"
