(load-file "~/.emacs.d/startup.el")
(load-file "~/.emacs.d/ui.el")
(load-file "~/.emacs.d/packaging.el")
(load-file "~/.emacs.d/editing.el")
(load-file "~/.emacs.d/project.el")
(load-file "~/.emacs.d/mail.el")
(load-file "~/.emacs.d/pythonista.el")
