(load-file "~/.emacs.d/startup.el")
(load-file "~/.emacs.d/ui.el")
(load-file "~/.emacs.d/packaging.el")
(load-file "~/.emacs.d/editing.el")
(load-file "~/.emacs.d/org.el")
(load-file "~/.emacs.d/pythonista.el")
(load-file "~/.emacs.d/rustacian.el")
