(source melpa)
(source "gnuhttp" "http://elpa.gnu.org/packages/")

(depends-on "use-package")

(depends-on "ace-window")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "yasnippet")
(depends-on "projectile")
(depends-on "company")
(depends-on "org-download")
(depends-on "org-roam")
(depends-on "ob-http")
(depends-on "ox-gfm")
(depends-on "rg")
(depends-on "editorconfig")
(depends-on "nord-theme")

(depends-on "markdown-mode")
(depends-on "web-mode")
(depends-on "plantuml-mode")

(depends-on "lsp-mode")
(depends-on "company-lsp")
(depends-on "lsp-ui")

(depends-on "rust-mode")
(depends-on "cargo")
