[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "python"
roots = ["pyproject.toml", "pyrightconfig.json", "setup.py"]
language-servers = ["pyright", "ruff"]
formatter = { command = "black", args = ["-", "-q"] }
