- name: install nix develop tools
  pacman:
    state: installed
    package:
    - strace
    - ltrace
    - lsof
    - valgrind
    - binutils
  become: yes

- name: install base-devel
  pacman:
    state: installed
    package:
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - file
    - findutils
    - flex
    - gawk
    - gcc
    - gettext
    - grep
    - groff
    - gzip
    - libtool
    - m4
    - make
    - patch
    - pkg-config
    - sed
    - socat
    - sudo
    - texinfo
    - util-linux
    - which
  become: yes
