- name: install git/mercurial/svn
  pacman:
    state: installed
    package:
    - git
    - mercurial
    - subversion
    - python-pre-commit
  become: true
- name: copy .gitconfig
  template: src=templates/gitconfig dest={{ ansible_env.HOME }}/.gitconfig
