- name: install mpd server and clients
  pacman:
    state: present
    package:
    - mpd
    - mpc
    - ncmpc
  become: true

- name: ensure .config/mpd exists
  file: path={{ ansible_env.HOME }}/.config/mpd state=directory recurse=yes

- name: ensure music dir exists
  file: path={{ ansible_env.HOME }}/music state=directory

- name: copy mpd.conf
  copy: src=templates/mpd.conf dest={{ ansible_env.HOME }}/.config/mpd/mpd.conf
  notify: restart mpd

- name: start mpd
  systemd: name=mpd scope=user state=started enabled=yes

- name: ensure .config/ncmpc exists
  file: path={{ ansible_env.HOME }}/.config/ncmpc state=directory recurse=yes

- name: copy ncmpc config
  copy: src=templates/ncmpc.conf dest={{ ansible_env.HOME }}/.config/ncmpc/config
